#!/usr/bin/env node
/* Embed assets/fonts/*.woff2 into index.html as base64 @font-face rules, between the
   EMBEDDED FONTS fence. Idempotent: run it again after fetch-fonts.js and it rewrites the
   block in place. On the very first run there is no fence yet, so it replaces the three
   Google Fonts <link> tags that used to sit at the top of <head>.

     node tools/fonts/inline-fonts.js
*/
const fs = require('fs'), path = require('path');

const ROOT  = path.join(__dirname, '..', '..');
const FONTS = path.join(ROOT, 'assets', 'fonts');
const HTML  = path.join(ROOT, 'index.html');
const START = '<!-- === EMBEDDED FONTS (generated by tools/fonts/inline-fonts.js) START === -->';
const END   = '<!-- === EMBEDDED FONTS END === -->';

// Inter ships as one variable file spanning the whole 400–700 range the UI uses; Saira Condensed
// ships as four statics. Order matters only for readability of the generated block.
const FACES = [
  { fam: 'Inter',           weight: '400 700', file: 'inter-var.woff2' },
  { fam: 'Saira Condensed', weight: '500',     file: 'saira-condensed-500.woff2' },
  { fam: 'Saira Condensed', weight: '600',     file: 'saira-condensed-600.woff2' },
  { fam: 'Saira Condensed', weight: '700',     file: 'saira-condensed-700.woff2' },
  { fam: 'Saira Condensed', weight: '800',     file: 'saira-condensed-800.woff2' },
];

let raw = 0;
const rules = FACES.map(f => {
  const buf = fs.readFileSync(path.join(FONTS, f.file));
  if (buf.slice(0, 4).toString() !== 'wOF2') throw new Error(f.file + ' is not a woff2 file');
  raw += buf.length;
  return `@font-face{font-family:'${f.fam}';font-style:normal;font-weight:${f.weight};font-display:swap;`
       + `src:url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2')}`;
}).join('\n');

const block = [
  START,
  '<style id="fonts">',
  '/* Saira Condensed 500/600/700/800 + Inter (variable, 400-700), latin subset, embedded as base64',
  '   woff2. Vendored rather than <link>ed: fonts.googleapis.com was the only external fetch in this',
  '   file, so offline -- and inside the iOS shell, which has no network origin at all -- the display',
  '   face fell back silently and took the whole look with it. Inlining also keeps index.html ONE',
  '   self-contained file, so the same bytes render identically from file://, from Pages over https://,',
  '   and from the app:// scheme the native shell serves -- no asset paths to resolve three ways.',
  '   Sources live in assets/fonts/ (committed: the gstatic URLs carry a version segment that rotates).',
  '   Regenerate: node tools/fonts/inline-fonts.js — refresh sources: node tools/fonts/fetch-fonts.js */',
  rules,
  '</style>',
  END,
].join('\n');

let html = fs.readFileSync(HTML, 'utf8');
const i = html.indexOf(START), j = html.indexOf(END);
if (i >= 0 && j > i) {
  html = html.slice(0, i) + block + html.slice(j + END.length);
} else {
  const links = /<link rel="preconnect" href="https:\/\/fonts\.googleapis\.com">[\s\S]*?<link href="https:\/\/fonts\.googleapis\.com\/css2[^>]*>/;
  if (!links.test(html)) throw new Error('no EMBEDDED FONTS fence and no Google Fonts <link> tags to replace');
  html = html.replace(links, block);
}
fs.writeFileSync(HTML, html);

const kb = n => (n / 1024).toFixed(0) + 'KB';
console.log(`embedded ${FACES.length} faces — ${kb(raw)} of woff2 → ${kb(block.length)} of base64`);
console.log(`index.html is now ${kb(Buffer.byteLength(html))}`);
